= Subproject `app`
:navtitle: `app`

The `app` subproject is structured as follows:

* `src/main/java` package `de.rptu.cs.exclaim`
 ** `controllers`: Business logic to handle incoming requests
 ** `data`: Custom POJOs extending the ones generated by jOOQ, for passing around aggregate data from the database
 ** `i18n`: All components for <<internationalization-i18n,internationalization>>
 ** `jobs`: <<non-recurring-background-jobs,Non-recurring background jobs>> to be executed asynchronously, outside the context of an HTTP request
 ** `monitoring`: Exception handling, generating application statistics
 ** `optimus`: The service that calculates an optimal group assignment based on preferences
 ** `runners`: Runners perform actions on application startup (e.g. processing the CLI options)
 ** `security`: Request processing, authentication, and authorization
 ** `utils`: Utilities and helpers
 ** `validation`: Extending the capabilities of `javax.validation`
 ** Classes in `exclaim` package:
  *** `DatabaseConfiguration`: Runtime configuration for <<flyway-migrations,Flyway>> and <<jooq,jOOQ>>
  *** `ExclaimApplication`: Startup and configure the Spring application
  *** `ExclaimProperties`: Declare custom <<configuration,configuration settings>>
  *** `ExclaimValidationProperties`: Declare constants that can be used in validation rules
  *** `Main`: CLI wrapper (for command line options)
  *** `Schedules`: <<recurring-background-tasks,Recurring background tasks>>
  *** `ThymeleafConfiguration`: Configuration for <<thymeleaf-templates,Thymeleaf>> to work with our <<internationalization-i18n,i18n>> classes
* `src/main/resources`
 ** `static`: Static files to be served by the webserver
 ** `templates`: See <<thymeleaf-templates,Thymeleaf Templates>>
 ** `application.properties`: Default <<configuration,configuration>> shipping with the application
 ** `messages_*.properties`: Translations, see <<internationalization-i18n,internationalization>>
* `src/test/java`: JUnit tests
