= Execute ExClaim

IMPORTANT: Remember that there is a different `.jar` file for each xref:ROOT:database-variants.adoc[supported database variant].

NOTE: If you have not been provided with the `.jar` file but the whole source code repository, then see the xref:developer-documentation:build:tasks/boot-jar.adoc[Developer Documentation] how to build the `.jar` file yourself.

[#execute]
== Execute

Open a terminal, navigate to the directory with the `.jar` file and execute:

.Start ExClaim with the H2 database variant
[source,bash]
----
java -jar exclaim-h2.jar
----

.Start ExClaim with the PostgreSQL database variant
[source,bash]
----
java -jar exclaim-postgresql.jar
----


[#access]
== Access the Application

Open the _Application URL_ that is shown in the terminal below the ExClaim logo.
Without any special xref:configuration:web-server.adoc[configuration], this is http://localhost:8080.

NOTE: The application is ready only after the message "`Tomcat started on port 8080 (http) with context path ''`" has been logged, not directly when the logo is shown.
  You therefore might need to wait a few seconds before you can open the provided URL, especially on the first start when the database is empty.

In order to login, you first need to xref:create-admin-account.adoc[create an admin account].
