import { apply, buildLexer, type Parser, tok } from 'typescript-parsec';

export const enum Tok {
  Dot,
  Hole,
  LBrace,
  RBrace,
  EmptySet,
  LAngle,
  RAngle,
  Comma,
  LParen,
  RParen,
  Plus,
  Minus,
  Star,
  Div,
  Mod,
  Eq,
  NEq,
  Lt,
  Gt,
  Leq,
  Geq,
  Colon,
  Arrow,
  If,
  Then,
  Else,
  Let,
  Rec,
  In,
  Fun,
  True,
  False,
  Bang,
  Assignment,
  NumberLiteral,
  CharLiteral,
  Identifier,
  Space,
}

export const lexer = buildLexer([
  [true, /^\?/g, Tok.Hole],
  [true, /^\{/g, Tok.LBrace],
  [true, /^\}/g, Tok.RBrace],
  [true, /^\u2205/g, Tok.EmptySet],
  [true, /^\u2329/g, Tok.LAngle],
  [true, /^\u232a/g, Tok.RAngle],
  [true, /^,/g, Tok.Comma],
  [true, /^\(/g, Tok.LParen],
  [true, /^\)/g, Tok.RParen],
  [true, /^\+/g, Tok.Plus],
  [true, /^(-|\u2238)/g, Tok.Minus],
  [true, /^\*/g, Tok.Star],
  [true, /^\//g, Tok.Div],
  [true, /^%/g, Tok.Mod],
  [true, /^=/g, Tok.Eq],
  [true, /^<>/g, Tok.NEq],
  [true, /^</g, Tok.Lt],
  [true, /^>/g, Tok.Gt],
  [true, /^<=/g, Tok.Leq],
  [true, /^>=/g, Tok.Geq],
  [true, /^:/g, Tok.Colon],
  [true, /^(->|\u2192|\u21a6)/g, Tok.Arrow],
  [true, /^(\.|\u00b7)/g, Tok.Dot],
  [true, /^if/g, Tok.If],
  [true, /^then/g, Tok.Then],
  [true, /^else/g, Tok.Else],
  [true, /^let/g, Tok.Let],
  [true, /^rec/g, Tok.Rec],
  [true, /^in/g, Tok.In],
  [true, /^fun/g, Tok.Fun],
  [true, /^true/g, Tok.True],
  [true, /^false/g, Tok.False],
  [true, /^!/g, Tok.Bang],
  [true, /^:=/g, Tok.Assignment],
  [true, /^\d+/g, Tok.NumberLiteral],
  [true, /^'([^'\\]|\\['\\])'/g, Tok.CharLiteral],
  [true, /^[A-Za-z_][A-Za-z0-9_]*/g, Tok.Identifier], // must come below all keywords
  [false, /^\s+/g, Tok.Space],
]);

export const NumberLiteralParser: Parser<Tok, bigint> = apply(tok(Tok.NumberLiteral), (t) => BigInt(t.text));
export const CharLiteralParser: Parser<Tok, string> = apply(tok(Tok.CharLiteral), (t) => {
  // remove surrounding single quotes
  const char = t.text.slice(1, -1);
  // remove leading escape character
  return char.startsWith('\\') ? char.slice(1) : char;
});
