= Join a Course

. On the home page, press the "Join a course" button.

. From the list of available courses, pick the one you want to register for and press the "Join" button.
+
--
NOTE: Only courses that you have not yet joined are listed here.
  If you cannot find the course you are looking for, check the home page whether you have already joined it.

NOTE: Registration is available only for a limited time.
  If your course does not appear in the list and you have not already joined it, then you probably have missed the registration deadline.
  You could ask the person responsible for your course if they are still able to add you.
--

. In order to participate in the exercises you also need to be assigned to a group.
  Depending on the group assignment method in use for your course, you see one of the following pages:

* A page with an overview of all groups in that course.
  Find a group that is not yet full (check the "Mitglieder" number) and hit the "Eintragen" button.
+
--
NOTE: You can use the "Austragen" button to leave your group and then join another group.

NOTE: To access this page again: visit the home page, click the course name and then hit the "Gruppen" button.

NOTE: If all groups are full you should ask the person responsible for your course what to do.
--

* A page that asks for your preferences. For each group, select...
+
--
** "Bevorzugt" if you prefer that time slot
** "Möglich" if you can arrange it
** "Ungern" if you could arrange it but actually do not like it
** "Unmöglich" if the slot is not possible for you because you have another university course at the same time.

IMPORTANT: Make sure to select a preference for each group.
  Groups without selection are treated as "Möglich".

IMPORTANT: Don't forget to save your settings by clicking the "Absenden" button at the bottom of the page.

Furthermore, you can provide the ExClaim usernames of your friends.
We will then try to assign you and your friends to the same group.

IMPORTANT: Make sure that you and your friends have similar group preferences.
  Adding friends in general, especial when group preferences diverge, shrink the chances of getting assigned to the a preferred group since it sometimes is impossible to find a solution that meets all preferences and still is conform with the group size constraints.

NOTE: To access this page again: visit the home page, click the course name and then hit the "Gruppen" button and then the "Gruppenpräferenzen angeben" button.

You will be assigned to a group when the person responsible for your course runs the assignment algorithm.
Check the course overview page (on the ExClaim home page, click the name of your course) to see your group.

NOTE: "Message: "Du bist noch nicht in eine Gruppe eingetragen.""
    This message is normal and disappears as soon as the assignment is done by the person responsible for your course.
    If the group registration is still open you can check and change your preferences by clicking the buttons "Gruppen" and "Gruppenpräferenzen angeben".
--

* An overview page for the course you just registered to.
  Click the "Gruppen" button to see an overview of all groups in that course.
  Check whether you can register for a group or enter your group preferences with one of the methods described above.
+
--
NOTE: If there is a message that group registration is closed then should check whether you missed the registration deadline or the group registration has not yet opened.
  In doubt, ask the person responsible for your course what to do.
--

. Before you can xref:submit-assignments.adoc[submit assignments], you need to be assigned to a team.
  Please tell your group tutor the names of other students that you want to work with.
  All team members must be in the same group.
